<rule-set declaration="" name="Tests assignment rules" xmlns="http://drools.org/rules"
 xmlns:java="http://drools.org/semantics/java"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 
<java:import>com.tornado.genmis.struts.GenMisForm</java:import>
<java:import>com.tornado.genmis.castorgen.Table</java:import>
<java:import>com.tornado.genmis.core.SrvContext</java:import>
<java:import>com.tornado.genmis.db.DBTransaction</java:import>
<java:import>com.tornado.genmis.exception.Warning</java:import>
<java:import>com.tornado.genmis.util.*</java:import>
<java:import>java.lang.String</java:import>  

<application-data identifier="table">Table</application-data>
<application-data identifier="tx">DBTransaction</application-data>
<application-data identifier="context">SrvContext</application-data>

<java:functions>
   <!--
   public static void getValue(String name) {
   } 
   public static void setValue(String name, String value) {
   }
   -->
</java:functions>


<rule name="JudgeStatus" salience="0">
   <parameter identifier="form">
      <java:class>
         GenMisForm
      </java:class>
   </parameter>
   <java:condition>!form.getParameter("STATUS").equals("0")</java:condition>
   <java:condition>!form.getParameter("STATUS").equals("4")</java:condition>
   <java:consequence>
      throw new Warning("不能修改处理中或者关闭的问题！");
   </java:consequence>
</rule>

<rule name="JudgeUser" salience="0">
   <parameter identifier="form">
      <java:class>
         GenMisForm
      </java:class>
   </parameter>
   <java:condition>!form.getParameter("MAKEUSERID").equals(context.getUser().getID())</java:condition>
   <java:consequence>
      throw new Warning("无权修改其他人提出的问题!");
   </java:consequence>
</rule>

<rule name="SetStatus5" salience="0">
   <parameter identifier="form">
      <java:class>
         GenMisForm
      </java:class>
   </parameter>
   <java:condition>!StringUtil.isBlankOrNull(form.getParameter("NEXTDEALER")) || !StringUtil.isBlankOrNull(form.getParameter("NEXTROLE"))</java:condition>
   <java:consequence>
      form.setParameter("STATUS","5");
   </java:consequence>
</rule>

<rule name="SetStatus0" salience="0">
   <parameter identifier="form">
      <java:class>
         GenMisForm
      </java:class>
    </parameter>
   <java:condition>StringUtil.isBlankOrNull(form.getParameter("NEXTDEALER"))</java:condition>
   <java:condition>StringUtil.isBlankOrNull(form.getParameter("NEXTROLE"))</java:condition>
   <java:consequence>
      form.setParameter("STATUS","0");
   </java:consequence>
</rule>

</rule-set>
