<rule-set declaration="" name="Tests assignment rules" xmlns="http://drools.org/rules"
 xmlns:java="http://drools.org/semantics/java"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 
<java:import>com.tornado.genmis.core.strutsGenMisForm</java:import>
<java:import>com.tornado.genmis.castorgen.Table</java:import>
<java:import>com.tornado.genmis.core.SrvContext</java:import>
<java:import>com.tornado.genmis.db.DBTransaction</java:import>
<java:import>com.tornado.genmis.exception.Warning</java:import>
<java:import>com.zhouxw.utils.string.StringUtil</java:import>
<java:import>java.lang.String</java:import>  

<application-data identifier="table">Table</application-data>
<application-data identifier="tx">DBTransaction</application-data>
<application-data identifier="context">SrvContext</application-data>

<java:functions>
   <!--
   public static void getValue(String name) {
   } 
   public static void setValue(String name, String value) {
   }
   -->
</java:functions>

<rule name="JudgeStauts04" salience="0">
   <parameter identifier="form">
      <java:class>
         GenMisForm
      </java:class>
   </parameter>
   <java:condition>form.getParameter("STATUS").equals("0") || form.getParameter("STATUS").equals("4")</java:condition>
   <java:consequence>
      throw new Warning("该问题还没有分配！");
   </java:consequence>
</rule>

<rule name="JudgeStauts3" salience="0">
   <parameter identifier="form">
      <java:class>
         GenMisForm
      </java:class>
   </parameter>
   <java:condition>form.getParameter("STATUS").equals("3")</java:condition>
   <java:consequence>
      throw new Warning("该问题已经关闭！");
   </java:consequence>
</rule>

<rule name="JudgeUser" salience="0">
   <parameter identifier="form">
      <java:class>
         GenMisForm
      </java:class>
   </parameter>
   <java:condition>!form.getParameter("NEXTDEALER").equals(context.getUser().getID())</java:condition>
   <java:consequence>
      throw new Warning("无权修改分配给其他人的问题！");
   </java:consequence>
</rule>

</rule-set>
