<rule-set declaration="" name="Tests assignment rules" xmlns="http://drools.org/rules"
 xmlns:java="http://drools.org/semantics/java"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 

<java:import>com.tornado.genmis.core.*</java:import>
<java:import>com.tornado.genmis.core.db.*</java:import>
<java:import>com.tornado.genmis.core.exception.*</java:import>
<java:import>com.tornado.genmis.core.struts.*</java:import>
<java:import>com.tornado.genmis.core.paging.*</java:import>

<java:import>com.tornado.genmis.castorgen.*</java:import>
<java:import>com.tornado.genmis.util.*</java:import>

<java:import>java.math.BigDecimal</java:import>
<java:import>java.lang.String</java:import>  

<application-data identifier="table">Table</application-data>
<application-data identifier="tx">DBTransaction</application-data>
<application-data identifier="context">SrvContext</application-data>

<java:functions>
   <!--
   public static void getValue(String name) {
   } 
   public static void setValue(String name, String value) {
   }
   -->
</java:functions>

<rule name="JudgeStatus" salience="0">
   <parameter identifier="form">
      <java:class>
         GenMisForm
      </java:class>
   </parameter>
   <java:condition>!StringUtil.isBlankOrNull(form.getParameter("HEADID"))</java:condition>
   <java:consequence>
      DBManager dbm = new DBManagerFactory().getDBManager(tx);
      Table hTable = ConfigUtil.getTable(table.getName().replaceAll("_DETAIL",""));
      GenMisForm hform = dbm.findByPK(hTable, new BigDecimal(form.getParameter("HEADID")), context);
      if (StringUtil.isBlankOrNull(hform.getParameter("ID"))) {
          throw new Warning("无法获取单据头表数据!");
      }
      if (hform.getParameter("STATUS").equals("2")) {
          throw new Warning("不能修改确认的单据明细数据!");
      }
      if (hform.getParameter("STATUS").equals("3")) {
          throw new Warning("不能修改作废的单据明细数据!");
      }
   </java:consequence>
</rule>

</rule-set>
