<rule-set declaration="" name="Tests assignment rules" xmlns="http://drools.org/rules" xmlns:java="http://drools.org/semantics/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<java:import>com.haiyan.genmis.core.db.DBManager</java:import>
	<java:import>com.haiyan.genmis.core.struts.GenMisForm</java:import>
	<java:import>com.haiyan.genmis.core.SrvContext</java:import>
	<java:import>com.haiyan.genmis.core.right.User</java:import>
	<java:import>com.haiyan.genmis.core.exception.*</java:import>
	<java:import>com.haiyan.genmis.castorgen.Table</java:import>
	<java:import>com.haiyan.genmis.util.StringUtil</java:import>
	<java:import>haiyan.interceptor.DroolsInterceptor</java:import>
	<java:import>java.lang.String</java:import>
	<application-data identifier="dbm">DBManager</application-data>
	<application-data identifier="table">Table</application-data>
	<application-data identifier="context">SrvContext</application-data>
	<java:functions>
		<!--
   public static void getValue(String name) {
   } 
   public static void setValue(String name, String value) {
   }
   -->
	</java:functions>
	<rule name="JudgeStatus" salience="0">
		<parameter identifier="form">
			<java:class>
         GenMisForm
      </java:class>
		</parameter>
		<java:condition>form.getParameter("STATUS").equals("2")</java:condition>
		<java:consequence>
      throw new Warning("确认后的单据不能修改!");
   </java:consequence>
	</rule>
</rule-set>
