<?xml version="1.0" encoding="GBK"?>
<rule-set declaration="" name="Tests assignment rules" xmlns="http://drools.org/rules" xmlns:java="http://drools.org/semantics/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<java:import>com.haiyan.genmis.core.db.DBManager</java:import>
	<java:import>com.haiyan.genmis.core.struts.GenMisForm</java:import>
	<java:import>com.haiyan.genmis.core.SrvContext</java:import>
	<java:import>com.haiyan.genmis.core.exception.Warning</java:import>
	<java:import>com.haiyan.genmis.castorgen.Table</java:import>
	<java:import>com.haiyan.genmis.util.StringUtil</java:import>
	<java:import>haiyan.interceptor.DroolsInterceptor</java:import>
	<java:import>java.lang.String</java:import>
	<application-data identifier="table">Table</application-data>
	<application-data identifier="dbm">DBManager</application-data>
	<application-data identifier="context">SrvContext</application-data>
	<rule name="run" salience="0">
		<parameter identifier="form">
			<java:class>GenMisForm</java:class>
		</parameter>
		<java:condition>"0".equals("0")</java:condition>
		<java:consequence>
		com.haiyan.genmis.core.paging.Page pg = dbm.findByFilter(table, null, 50, 1, context, null);
		// System.out.println("........"+pg.toXML(table));
       context.write(pg.toXML(table));
       // throw new Exception(str);
       </java:consequence>
	</rule>
</rule-set>
